import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import CodeLayout from "@/components/Layout/CodeLayout";

const fontFamily = Fira_Code({
  variable: "--font-main",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontFamily.variable} antialiased`}>
        <CodeLayout>{children}</CodeLayout>
      </body>
    </html>
  );
}
