import Head from 'next/head'
import Navbar from "components/Navbar"
import Header from "components/Header"
import IntroSection from "components/IntroSection"
import SkillsSection from "components/SkillsSection"
import ProjectsSection from "components/ProjectsSection"
import Footer from "components/Footer"

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio - Imesh Nimsitha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="transition duration-300 bg-light dark:bg-jet w-full">
        <Header />
        <div id="intro">
          <IntroSection />
        </div>
        <div id="skills">
          <SkillsSection />
        </div>
        <div id="projects">
          <ProjectsSection />
        </div>
			  <Footer />
		</div>
    </>
  )
}
